### ISSUE TITLE
Not work with redmine 3.1.2

### ISSUE THREAD

**Issue by belaytzev** [ares/redmine_omniauth_github#2]
Problem repeat at:

Environment:
  Redmine version                3.1.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.0.0
  clipboard_image_paste          1.10
  extra_queries                  2.0.3
  redmine_agile                  1.3.12
  redmine_change_issue_author    0.0.1
  redmine_checklists             3.1.3
  redmine_create_wiki_page       0.1
  redmine_hipchat                2.0.0
  redmine_issue_tabs             1.1.1
  redmine_lightbox2              0.2.4
  redmine_my_page_queries        2.1.6
  redmine_preview_attach_column  0.1.7
  redmine_tweetbook              1.0
  status_button                  0.1.0
  usability                      2.1.0

When first redirect on Github work normaily, but after allow permissions callback url redirect to login page redmine

**Comment by ares** [comment]
Hello, thanks for the report, I'm currently not running Redmine 3+ anywhere so I won't get to fixing anytime soon. Please look at this fork https://github.com/jeromelebleu/redmine_omniauth_github that claims to have 3.x support. If it works I'm happy to bring fixing patches back (the fork author didn't send a pull request :-/)

**Comment by belaytzev** [comment]
Try to install https://github.com/jeromelebleu/redmine_omniauth_github but it steel not work(

**Comment by jeromelebleu** [comment]
Sorry about not sending you a pull request sooner, time goes too fast... Here is it: https://github.com/ares/redmine_omniauth_github/pull/3.

Tell me if you can try with older versions and if it's still working... But also if you see some improvements to do and at least if you will plan to merge it! :)

**Comment by belaytzev** [comment]
Thanks, i already fix my problem, just change call back url to /oauth/github/callback
