### ISSUE TITLE
Error: column users.mail does not exist

### ISSUE THREAD

**Issue by debfx** [ares/redmine_omniauth_github#4]
With redmine_omniauth_github 0.0.2 and Redmine 3.1 I get the following error:
PG::UndefinedColumn: ERROR:  column users.mail does not exist

Seems like in Redmine 3 the users.mail column has been moved to a separate table as an account can have multiple email addresses.

This patch seems to fix this but I'm not fluent in Ruby so take this with a grain of salt:
```diff
--- a/app/controllers/redmine_oauth_controller.rb
+++ b/app/controllers/redmine_oauth_controller.rb
@@ -36,7 +36,7 @@ class RedmineOauthController < AccountController
       unverified = emails.select { |e| !e['verified'] }.map { |v| v['email'] }
       primary = emails.select { |e| e['primary'] }.first.try(:[], 'email')
 
-      if (user = User.where(:mail => verified).first)
+      if (user = User.joins(:email_addresses).where(:email_addresses => { :address => verified }).first)
         checked_try_to_login user.mail, user_info, user
       else
         if User.find_by_mail(unverified).nil? && verified.include?(primary)
```

**Comment by debfx** [comment]
Or maybe User.find_by_mail() since it seems to be able to handle an array of addresses as input (at least in 3.1).

**Comment by ares** [comment]
Thanks for the patch. I will have to test it with older version (2.6.9) and make the change compatible, but I'll be happy to get it in afterwards.

**Comment by ares** [comment]
Seems like this was added in 3.0.0 https://github.com/redmine/redmine/blob/3.0.0/db/migrate/20150113213922_remove_users_mail.rb

@debfx I've added a fix in https://github.com/ares/redmine_omniauth_github/commit/7c44c8e8ec33c882634705c5dc87fe2e605185fe could you please test it and verify it works for you? I'd tag it then.

**Comment by ares** [comment]
@debfx ping?

**Comment by debfx** [comment]
Works fine with 3.2.1, thanks a lot!

**Comment by ares** [comment]
Thanks for confirmation, tagged as 0.0.3
